apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app-deployment1
spec:
  selector:
    matchLabels:
      app: spring-boot-app1
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-app1
    spec:
      containers:
      - name: spring-boot-app1
        image: praravind1801/ingress-backend:v1
        ports:
        - containerPort: 8080
